# Generated by Django 4.2.4 on 2023-08-30 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nexus', '0007_department_alter_course_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='department',
            field=models.CharField(choices=[('Science', 'Science'), ('Arts', 'Arts'), ('Engineering', 'Engineering')], max_length=50),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='department',
            field=models.CharField(choices=[('Science', 'Science'), ('Arts', 'Arts'), ('Engineering', 'Engineering')], max_length=50),
        ),
    ]
