# Generated by Django 4.2.4 on 2023-08-30 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Nexus', '0008_alter_course_department_alter_instructor_department'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'managed': False},
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('publish_date', models.DateField()),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Nexus.course')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Nexus.department')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Nexus.instructor')),
            ],
        ),
    ]
