# Generated by Django 4.2.4 on 2023-08-30 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Nexus', '0010_assignment_course_name_alter_announcement_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='course_name',
            new_name='name',
        ),
    ]
