# Generated by Django 4.2.4 on 2023-08-31 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nexus', '0012_alter_assignment_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='imageUrl',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='student',
            name='imageUrl',
            field=models.URLField(blank=True),
        ),
    ]
