# Generated by Django 4.2.4 on 2023-08-31 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nexus', '0013_instructor_imageurl_student_imageurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='imageUrl',
            field=models.URLField(blank=True),
        ),
    ]
